global:
  scrape_interval:     40s
  evaluation_interval: 40s

scrape_configs:
  - job_name: 'music'
    static_configs:
      - targets: ['2021_1_noskool_team_music-service_1:8888']

  - job_name: 'profiles'
    static_configs:
      - targets: ['2021_1_noskool_team_profiles-service_1:8082']

  - job_name: node
    static_configs:
      - targets: [ 'node_exporter:9100' ]