music_server_addr = ":8080"

session_microservice_addr = ":8081"
session_redis_url = "redis://127.0.0.1:6379/0"
#session_redis_url = "redis://redis/0"

log_level = "debug"

music_bd = "host=localhost port=5432 dbname=music_service sslmode=disable"
#music_bd = "host=music-bd port=5432 user=andrewkireev dbname=music_service password=password sslmode=disable"