music_server_addr = "127.0.0.1:8080"

session_microservice_addr = "127.0.0.1:8081"
session_redis_url = "redis://user:@localhost:6379/0"

profiles_server_addr = "127.0.0.1:8082"


profiles_db_url = "host=localhost dbname=profiles_dev port=5432 sslmode=disable"

log_level = "debug"