music_server_addr = ":8888"
#session_microservice_addr = ":8081"
session_microservice_addr = "sessions-service:8081"
#session_redis_url = "redis://127.0.0.1:6379/0"
session_redis_url = "redis://redis/0"
log_level = "debug"
#music_bd = "host=localhost port=5432 dbname=music_service sslmode=disable"
music_bd = "host=music-bd port=5432 user=andrewkireev dbname=music_service password=password sslmode=disable"
profiles_server_addr = ":8082"
#profiles_db_url = "host=localhost dbname=profiles_dev port=5432 sslmode=disable"
profiles_db_url = "host=music-bd port=5432 user=andrewkireev dbname=music_service password=password sslmode=disable"
#profiles_db_url = "host=localhost dbname=music_service port=5432 sslmode=disable"
frontend_url = "http://178.154.245.200:80"